### ISSUE TITLE
Extension show NaN days left randomly on load

### ISSUE THREAD

**Issue by Mariomm-marti** [Bidijoe45/white-nova-extension#1]
## Issue
When loading the intranet with the extension, it fails to show the amount of remaining days with NaN days at random (70% of failure).
<img width="902" alt="image" src="https://user-images.githubusercontent.com/24687973/186234167-77ae03f2-a9d7-4bae-a553-87a69c89c32c.png">

# Details
Extension release v2.0.0
Google Chrome Version 98.0.4758.80
MacOS Mojave 10.14.5
https://profile.intra.42.fr

**Comment by Bidijoe45** [comment]
Bug has been fixed. Will be deployed on release 2.0.1
