### ISSUE TITLE
Location on cycle change does not trim beginning date

### ISSUE THREAD

**Issue by Mariomm-marti** [Bidijoe45/white-nova-extension#4]
## Issue
If a location is shared between two cycles (eg. end of cycle 10am, location begin 6am end 6pm), the time is not trimmed to [cycle begin; location end].

## Proposed solution
On the endpoint, when fetching all locations from users take into consideration whether location.begin_at < cycle.begin_at and use cycle.begin_at to subtract instead.

## Details
Extension release v2.0.1
Google Chrome Version 104.0.5112.101
MacOS Mojave 10.14.5
https://profile.intra.42.fr/

**Comment by Bidijoe45** [comment]
Fixed
