### ISSUE TITLE
User data ignored when not extension user and not searched

### ISSUE THREAD

**Issue by Mariomm-marti** [Bidijoe45/white-nova-extension#5]
## Issue
When someone doesn't:
- use the extension
- and is not searched
His/her data will be totally ignored.

As an example:
- User X attends to the campus and connects (ie. creates a location)
- User X does not use the extension, and is not usually searched among his peers
- User X leaves the campus (ie. updates and ends a location)
- User Y looks for user X, therefore the last_search is updated, but data wasn't synchronized and user is ignored

### 1. Manual synchronize on first lookup (preferred)
Create an endpoint on the backend/synchronizer that allows manual user update (eg. synchronizer/update/<login>).
This endpoint should fetch all data from the user every since the last_search.
Pros:
- update on demand
- almost real time (some seconds of delay)
Cons:
- violation of SRP
- increase number of request if someone spams update on people not searched in the past 24 hours

### 2. Create different time-span update cycles
If a location is updated every 10 seconds, create bigger cycles (eg. every 10 minutes) that synchronize all other users not being taken into consideration
Pros:
- synchronizer stays stand-alone
Cons:
- request number increase
- on worst case scenario, the affected users (ie. no extension + not searched) have to wait up to 10 minutes to get their new data

## Details
Extension release v2.0.1
Google Chrome Version 104.0.5112.101
MacOS Mojave 10.14.5
https://profile.intra.42.fr/

**Comment by Bidijoe45** [comment]
Fixed!
