### ISSUE TITLE
Extension Isn't Working (Buttons Won't Toggle)

### ISSUE THREAD

**Issue by TakuyaSama** [Bidijoe45/white-nova-extension#7]
Hello fellows 42 students,
Since yesterday, I've been experiencing issues with the White Nova Intra requirements, I provide an screenshot to show an example of what's the actual behavior, which results into a incapacity to interact with the toggles to activate or deactivate the White Nova info/requirements.
My guess is that there's been changes in 42's API, so that should explain why the extension stopped working properly.
The extension is **REALLY** helpful and useful, so it's such a shame it stopped working.
I'm more than open to help, if I'm able, to fix this.
The actual status of the extension on the Intra:
![imagen](https://user-images.githubusercontent.com/15946300/196909781-f44e9fd0-5085-4592-a193-466c7c506bb4.png)

<h1>Details</h1>

**Extension version**: 2.0.1
**Web Browser**: Firefox 98.0.1
**OS**: macOS Catalina 10.15.7 (19H15)
https://profile.intra.42.fr/

Thank you very much for your work, efforts, time and contribution to 42 Madrid 😀.
Receive a huge, strong, sincere & virtual hug from a fellow 42 Madrid student, as well as my best desires ˆˆ.

**Comment by Bidijoe45** [comment]
Hello! Thank you for reporting it. This is not an issue related to the extension. The intranet was updated and the identifiers of the containers changed. When I am sure there will be no more updates, I will update the extension.

**Comment by TakuyaSama** [comment]
Perfect, thank you very much.
I guessed it was an 42's Intra/API change, so it's that.
Thank you very much for your quick response Adrian 😀.
I'll let others students who face this and tell me or I see on Slack know the reason then.
Bests regards 😄.
