### ISSUE TITLE
Maybe a typo, 🤔

### ISSUE THREAD

**Issue by rapejim** [Bidijoe45/white-nova-extension#9]
I was looking at the code and I saw a... typo?:
"**_flter[blackhole]_**" instead "**_filter[blackhole]_**" 🤔 

https://github.com/Bidijoe45/white-nova-extension/blob/97581e499c0ebc05d5100f892066e07ef932bebc/backend/synchronizer/sync/users.py#L18

**Comment by Bidijoe45** [comment]
Hello @rapejim, yes you are right, thank you!
